// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2DlVme20l07fXKg-MYxrjqebEU2d6ZNY',
    appId: '1:246513545707:web:513e571d8c5289722ae9ae',
    messagingSenderId: '246513545707',
    projectId: 'tiktok-sinwon',
    authDomain: 'tiktok-sinwon.firebaseapp.com',
    storageBucket: 'tiktok-sinwon.appspot.com',
    measurementId: 'G-12BK9RS2M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ZcjviJgPzaX3x7ygcbYd3Osnc-kqE_U',
    appId: '1:246513545707:android:4b000a9d78357c242ae9ae',
    messagingSenderId: '246513545707',
    projectId: 'tiktok-sinwon',
    storageBucket: 'tiktok-sinwon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQy0quppv_zuxjSMyDZMuXNLbcdKrjTo',
    appId: '1:246513545707:ios:2115f68f0b0b0c372ae9ae',
    messagingSenderId: '246513545707',
    projectId: 'tiktok-sinwon',
    storageBucket: 'tiktok-sinwon.appspot.com',
    iosClientId:
        '246513545707-m8nvobuu5difu7nuu4cdp36c6mliugd9.apps.googleusercontent.com',
    iosBundleId: 'co.halfbaek.tiktok',
  );
}
